server:
  port: 8000
spring:
  profiles:
    include: env
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${env.datasource.url}
    username: ${env.datasource.username}
    password: ${env.datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ${env.kakao.client-id}
            client-secret: ${env.kakao.client-secret}
            client-authentication-method: POST
            redirect-uri: ${env.kakao.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
properties:
  secretKey: ${env.properties.secretKey}
  accessTokenExpire: 1
  refreshTokenExpire: 168
  authorizedUri: http://localhost:3000
