env:
  properties:
    secretKey: 926D96C90030DD58429D2751AC1BDBBC
    redirectUri: http://localhost:8080/oauth2/redirect
  datasource:
    url: jdbc:mysql://localhost:3306/whiteblue
    username: root
    password: root
  kakao:
    client-id: d2a8f624c9f01d5153378d193c4d0452
    client-secret: IogwIMFb3jIJSNK68MtGywbWYktyeXfN
    redirect-uri: http://localhost:8000/oauth/redirect/kakao
